#This script calculate the scaled TPM of the RNA-seq data.

library(edgeR)

#This is a function which removes version from ensembl IDs.
StripVer <- function(ID){
  N <- regexpr("\\.", ID)[[1]]
  return(substr(ID, 1, N-1))
}

f <- "Path to your RNA-seq counts file generated by 'featureCounts.sh'"

counts <- read.delim(f, skip=1, row.names=1)
counts <- counts[,!colnames(counts) %in% c("Chr", "Start", "End", "Strand")]

counts_tpm <- (counts[,2:ncol(counts)]/counts$Length)*1000

normfactor <- DGEList(counts = counts_tpm,
                      group = colnames(counts_tpm))
normfactor <- calcNormFactors(normfactor, method="RLE")
normfactor_samples <- normfactor$samples
normfactor_samples$normlib <- normfactor_samples$lib.size*normfactor_samples$norm.factors

for(i in 1:ncol(counts_tpm)){
  counts_tpm[,i] <- (counts_tpm[,i]/normfactor_samples$normlib[i])*1000000 
}

#Remove version from ensembl IDs
rownames(counts_tpm) <- Vectorize(StripVer)(rownames(counts_tpm))

#Save
write.csv(counts_tpm, file = "Scaled_TPM.csv")