library(clusterProfiler)
library(org.Mm.eg.db)
library(tidyverse)
library(pals)

get_anno <- function(data){
  df <- read.csv(data, header = T, stringsAsFactors = F, sep = "\t")
  colnames(df)[1] <- "PeakID"
  colnames(df)[12] <- "ENSEMBL"
  return(df)
}

komoji2omoji <- function(string){
  omoji <- toupper(substr(string, 1, 1))
  sento_igai <- substr(string, 2, nchar(string))
  return(paste0(omoji,sento_igai))
}

get_custom_plot <- function(ck_simp, selected_terms_by_dotplot){
  
  ck_simp <- as.data.frame(ck_simp)
  
  selected_terms_by_dotplot <- selected_terms_by_dotplot %>% rev() %>% Vectorize(komoji2omoji)()
  
  ck_simp$Description <- Vectorize(komoji2omoji)(ck_simp$Description)
  
  ck_simp <- subset(ck_simp, Description %in% selected_terms_by_dotplot)
  ck_simp$Description <- factor(ck_simp$Description, levels = sort(selected_terms_by_dotplot, decreasing = T))
  
  g <- ggplot(ck_simp, aes(x = Cluster, y = Description, fill = -log10(p.adjust)))+
    geom_tile()+
    theme_bw()+
    guides(size=guide_legend(title="-log10 p.adjust"))+
    guides(color = F)+
    theme(axis.title = element_blank())+
    theme(axis.text = element_text(size = 20))+
    theme(legend.text = element_text(size = 12), legend.title = element_text(size = 12))+
    scale_fill_gradientn(colours=colorRampPalette(c("mistyrose", "darkorange1"))(100))+
    theme(panel.grid = element_blank(), strip.background = element_blank(), strip.text = element_blank())
  
  plot(g)
}


WT <- get_anno("Path to your 'WT_SE_annotated.txt' generated by 'findPeaks_annotatePeaks.sh'")
KO <- get_anno("Path to your 'KO_SE_annotated.txt' generated by 'findPeaks_annotatePeaks.sh'")

TPM <- read.csv("Path to your 'Scaled_TPM.csv' generated by 'Calculate_scaled_TPM_of_RNA-seq.R'", stringsAsFactors = F)

#Name columns of "TPM". In this script, "WT" and "KO" are scaled TPM of WT and Crk/Crkl KO cells respectively.
colnames(TPM) <- c("ENSEMBL", "WT", "KO", "XXX") 
                                                 

WT_with_TPM <- left_join(WT, TPM, by = "ENSEMBL") %>% distinct(ENSEMBL, .keep_all = TRUE)
WT_with_TPM <- subset(WT_with_TPM, WT > 1 | KO > 1) #Remove low expressing genes

KO_with_TPM <- left_join(KO, TPM, by = "ENSEMBL") %>% distinct(ENSEMBL, .keep_all = TRUE)
KO_with_TPM <- subset(KO_with_TPM, WT > 1 | KO > 1) #Remove low expressing genes

WT_ID <- unique(WT_with_TPM$Gene.Name)
KO_ID <- unique(KO_with_TPM$Gene.Name)

WT_ID <- bitr(WT_ID, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
KO_ID <- bitr(KO_ID, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")


cls <- list(WT = WT_ID$ENTREZID, KO = KO_ID$ENTREZID)

ck <- compareCluster(geneCluster = cls , fun = "enrichGO", OrgDb = "org.Mm.eg.db",
                     ont           = "BP",
                     pAdjustMethod = "BH",
                     pvalueCutoff  = 0.01,
                     qvalueCutoff  = 0.05,
                     readable      = TRUE)

ck_simp_WT_vs_KO <- clusterProfiler::simplify(ck, cutoff=0.7, by="p.adjust", select_fun=min)

dotplot(ck_simp_WT_vs_KO)

#See the plot by "dotplot(ck_simp_WT_vs_KO)" and write here the GO terms in it.
selected_terms_by_dotplot <- c("cell-substrate adhesion",
                               "actin filament organization",
                               "regulation of actin filament-based process",
                               "embryonic organ development",
                               "epithelial tube morphogenesis",
                               "striated muscle tissue development",
                               "positive regulation of cell adhesion",
                               "ossification",
                               "regulation of cellular response to growth factor stimulus",
                               "gland development")

get_custom_plot(ck_simp_WT_vs_KO, selected_terms_by_dotplot)